### ISSUE TITLE
Design for top window bar

### ISSUE THREAD

**Issue by talyguryn** [codex-team/hawk.desktop#28]
![image](https://user-images.githubusercontent.com/15259299/119548635-1550d200-bd9f-11eb-9ced-70e341c5e883.png)

**Comment by neSpecc** [comment]
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/3684889/120299613-d6a5a500-c2d3-11eb-869e-f455f9884253.png">

### Zeplin

- [macOS](https://zpl.io/bLqN17G)
- [Windows](https://zpl.io/bPB47RM)

**Comment by talyguryn** [comment]
resolved
