### ISSUE TITLE
hawk.desktop cannot be shown correctly

### ISSUE THREAD

**Issue by RrobertRr** [codex-team/hawk.desktop#37]
I installed the Hawk Desktop 0.0.10 on Windows with the [Hawk-Desktop-Setup-0.0.10.exe](https://github.com/codex-team/hawk.desktop/releases/download/v0.0.10/Hawk-Desktop-Setup-0.0.10.exe).

And after installation I can only see the following:
![image](https://user-images.githubusercontent.com/25011725/155956424-6a0b8363-c5fc-48a9-81ed-b97babfcab1e.png)

So Hawk is starting, but I can only see the top header, without body.

**Comment by RrobertRr** [comment]
I tested it on two different Windows PCs. with Win10.

**Comment by micc83** [comment]
Same on macOs 12.2.1:
<img width="740" alt="Schermata 2022-03-09 alle 12 36 43" src="https://user-images.githubusercontent.com/1750404/157434365-77086826-1bfd-4d16-b40a-d6f24f9fdc89.png">

**Comment by talyguryn** [comment]
sorry. resolved in [v0.0.11](https://github.com/codex-team/hawk.desktop/releases/tag/v0.0.11). please download the latest version manually.

**Comment by RrobertRr** [comment]
Now it works. Thanks.
